version: '3.8'
services:
  app:
    image: ramezzorgui/kaddem app:${IMAGE_TAG}  
    ports:
      - "8099:8099"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/kaddemdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=my-secret-pw
    depends_on:
      - mysql
    networks:
      - mynetwork
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "512M"

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=kaddemdb
    ports:
      - "3307:3306"  
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "768M"

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql-data:
